# Dynamic Prediction System: For AirBnb's

This model will be trained on the data by Airbnb's offical insider website, the data chosen is of new york city, and based on the all the training of the data with various model and predicting the best one out this system will give an output which can help the host to select the best price range for their listing, based on the Location and many other factors.

In [28]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np 
from sklearn.preprocessing import StandardScaler

In [29]:
Dataset = pd.read_csv('Data/listings.csv')

In [30]:
Dataset.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20251204025441,2025-12-06,previous scrape,Superfast Wi-Fi. Clean & quiet home by the park,"Bright, serene room in a renovated apartment h...",Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/hosting/Hosti...,2787,...,5.00,4.75,4.88,NaN,f,7,1,6,0,0.07
1,2595,https://www.airbnb.com/rooms/2595,20251204025441,2025-12-05,city scrape,Skylit Studio Oasis | Midtown Manhattan Sanctuary,Prime Midtown | Spacious 500 Sq Ft | Pyramid S...,Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/hosting/Hosti...,2845,...,4.80,4.81,4.40,NaN,f,3,3,0,0,0.24
2,6848,https://www.airbnb.com/rooms/6848,20251204025441,2025-12-04,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.80,4.69,4.59,NaN,f,1,1,0,0,0.98
3,6872,https://www.airbnb.com/rooms/6872,20251204025441,2025-12-05,city scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,This sweet Harlem sanctuary is a 10-20 minute ...,https://a0.muscache.com/pictures/miso/Hosting-...,16104,...,5.00,5.00,5.00,NaN,f,2,0,2,0,0.05
4,6990,https://www.airbnb.com/rooms/6990,20251204025441,2025-12-05,city scrape,UES Beautiful Blue Room,Beautiful peaceful healthy home,"Location: Five minutes to Central Park, Museum...",https://a0.muscache.com/pictures/45fb4ec7-6856...,16800,...,4.94,4.85,4.83,NaN,f,1,0,1,0,1.27

In [31]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36261 entries, 0 to 36260
Data columns (total 85 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            36261 non-null  int64
 1   listing_url                                   36261 non-null  object
 2   scrape_id                                     36261 non-null  int64
 3   last_scraped                                  36261 non-null  object
 4   source                                        36261 non-null  object
 5   name                                          36259 non-null  object
 6   description                                   34893 non-null  object
 7   neighborhood_overview                         18130 non-null  object
 8   picture_url                                   36261 non-null  object
 9   host_id                                       36261 non-null  int64
 10  host_url                                      36261 non-null  object
 11  host_profile_id                               35856 non-null  float64
 12  host_profile_url                              35856 non-null  object
 13  host_name                                     36250 non-null  object
 14  host_since                                    36250 non-null  object
 15  hosts_time_as_user_years                      35845 non-null  float64
 16  hosts_time_as_user_months                     35845 non-null  float64
 17  hosts_time_as_host_years                      35412 non-null  float64
 18  hosts_time_as_host_months                     35412 non-null  float64
 19  host_location                                 28393 non-null  object
 20  host_about                                    20778 non-null  object
 21  host_response_time                            21088 non-null  object
 22  host_response_rate                            21088 non-null  object
 23  host_acceptance_rate                          21520 non-null  object
 24  host_is_superhost                             36261 non-null  object
 25  host_thumbnail_url                            36250 non-null  object
 26  host_picture_url                              36250 non-null  object
 27  host_neighbourhood                            28882 non-null  object
 28  host_listings_count                           36250 non-null  float64
 29  host_total_listings_count                     36250 non-null  float64
 30  host_verifications                            36250 non-null  object
 31  host_has_profile_pic                          36250 non-null  object
 32  host_identity_verified                        36250 non-null  object
 33  neighbourhood                                 18131 non-null  object
 34  neighbourhood_cleansed                        36261 non-null  object
 35  neighbourhood_group_cleansed                  36261 non-null  object
 36  latitude                                      36261 non-null  float64
 37  longitude                                     36261 non-null  float64
 38  property_type                                 36261 non-null  object
 39  room_type                                     36261 non-null  object
 40  accommodates                                  36261 non-null  int64
 41  bathrooms                                     21455 non-null  float64
 42  bathrooms_text                                36153 non-null  object
 43  bedrooms                                      30248 non-null  float64
 44  beds                                          21370 non-null  float64
 45  amenities                                     36261 non-null  object
 46  price                                         0 non-null      float64
 47  minimum_nights                                36261 non-null  int64
 48  maximum_nights                                36261 non-null  int64
 49  minimum_minimum_nights                        36257 non-null  float64
 50  maximum_minimum_nights                        36257 non-null  float64
 51  minimum_maximum_nights                        36257 non-null  float64
 52  maximum_maximum_nights                        36257 non-null  float64
 53  minimum_nights_avg_ntm                        36261 non-null  float64
 54  maximum_nights_avg_ntm                        36261 non-null  float64
 55  calendar_updated                              0 non-null      float64
 56  has_availability                              30627 non-null  object
 57  availability_30                               36261 non-null  int64
 58  availability_60                               36261 non-null  int64
 59  availability_90                               36261 non-null  int64
 60  availability_365                              36261 non-null  int64
 61  calendar_last_scraped                         36261 non-null  object
 62  number_of_reviews                             36261 non-null  int64
 63  number_of_reviews_ltm                         36261 non-null  int64
 64  number_of_reviews_l30d                        36261 non-null  int64
 65  availability_eoy                              36261 non-null  int64
 66  number_of_reviews_ly                          36261 non-null  int64
 67  estimated_occupancy_l365d                     36261 non-null  int64
 68  estimated_revenue_l365d                       0 non-null      float64
 69  first_review                                  24912 non-null  object
 70  last_review                                   24912 non-null  object
 71  review_scores_rating                          24912 non-null  float64
 72  review_scores_accuracy                        24901 non-null  float64
 73  review_scores_cleanliness                     24910 non-null  float64
 74  review_scores_checkin                         24897 non-null  float64
 75  review_scores_communication                   24905 non-null  float64
 76  review_scores_location                        24894 non-null  float64
 77  review_scores_value                           24895 non-null  float64
 78  license                                       5028 non-null   object
 79  instant_bookable                              36261 non-null  object
 80  calculated_host_listings_count                36261 non-null  int64
 81  calculated_host_listings_count_entire_homes   36261 non-null  int64
 82  calculated_host_listings_count_private_rooms  36261 non-null  int64
 83  calculated_host_listings_count_shared_rooms   36261 non-null  int64
 84  reviews_per_month                             24912 non-null  float64
dtypes: float64(29), int64(20), object(36)
memory usage: 23.5+ MB

In [32]:
Dataset.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name',
       'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [33]:
dropping = ['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name','description', 'neighborhood_overview', 'picture_url',
            'host_id', 'calculated_host_listings_count','calculated_host_listings_count_entire_homes','calculated_host_listings_count_private_rooms',
            'calculated_host_listings_count_shared_rooms', 'host_url','host_profile_id','host_profile_url','host_name',
            'host_since','host_thumbnail_url','host_picture_url','host_location',
            'calendar_updated','calendar_last_scraped', 'host_about', 'hosts_time_as_host_years', 'hosts_time_as_host_months',
            'latitude', 'longitude','bathrooms_text','amenities','first_review', 'last_review', 'host_neighbourhood','host_has_profile_pic',
            'minimum_minimum_nights', 'maximum_minimum_nights',
            'minimum_maximum_nights', 'maximum_maximum_nights',
            'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm','has_availability',
            'availability_30', 'availability_60', 'availability_90',
            'availability_365',  'number_of_reviews_ltm',
            'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly',]

In [34]:
Dataset = Dataset.drop(dropping, axis = 1)

In [35]:
Dataset.head()

,hosts_time_as_user_years,hosts_time_as_user_months,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_identity_verified,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,reviews_per_month
0,17.0,2.0,within an hour,100%,79%,f,7.0,13.0,"['email', 'phone']",t,...,4.89,4.88,5.00,5.00,5.00,4.75,4.88,NaN,f,0.07
1,17.0,2.0,within a day,60%,26%,f,7.0,9.0,"['email', 'phone', 'work_email']",t,...,4.68,4.73,4.63,4.77,4.80,4.81,4.40,NaN,f,0.24
2,16.0,6.0,within an hour,100%,100%,t,1.0,1.0,"['email', 'phone']",t,...,4.60,4.60,4.85,4.85,4.80,4.69,4.59,NaN,f,0.98
3,16.0,6.0,within a day,70%,33%,f,2.0,2.0,"['email', 'phone', 'work_email']",t,...,5.00,5.00,5.00,5.00,5.00,5.00,5.00,NaN,f,0.05
4,16.0,6.0,within an hour,100%,100%,f,1.0,6.0,"['email', 'phone']",t,...,4.88,4.83,4.95,4.96,4.94,4.85,4.83,NaN,f,1.27

In [36]:
Dataset.columns

Index(['hosts_time_as_user_years', 'hosts_time_as_user_months',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed',
       'property_type', 'room_type', 'accommodates', 'bathrooms', 'bedrooms',
       'beds', 'price', 'minimum_nights', 'maximum_nights',
       'number_of_reviews', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'license',
       'instant_bookable', 'reviews_per_month'],
      dtype='object')